#################################################################
###################### NexT Configuration #######################
#################################################################

# ===============================================================
# It's recommended to use Alternate Theme Config to configure NexT
# Modifying this file may result in merge conflict
# See: https://theme-next.js.org/docs/getting-started/configuration
# ===============================================================

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.js.org/docs/theme-settings/
# ---------------------------------------------------------------

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini
darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

#favicon:
  #small: /images/favicon-16x16-next.png
  #medium: /images/favicon-32x32-next.png
  #apple_touch_icon: /images/apple-touch-icon-next.png
  #safari_pinned_tab: /images/logo.svg
  #android_manifest: /manifest.json

# Custom Logo (Warning: Do not support scheme Mist)
#custom_logo: /uploads/custom-logo.jpg

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/about/cclicenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  sidebar: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell

  Docs:
    default: /docs/ || fa fa-book

    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Deployment: /deployment.html || fa fa-upload
      Configuration: /configuration.html || fa fa-wrench
      Upgrade: /upgrade.html || fa fa-history

    Theme Settings:
      default: /theme-settings/ || fa fa-star
      Sidebar: /sidebar.html || fa fa-bars
      Footer: /footer.html || fa fa-sticky-note
      Posts: /posts.html || fa fa-paragraph
      Custom Pages: /custom-pages.html || fa fa-swatchbook
      Miscellaneous: /miscellaneous.html || fa fa-university
      SEO: /seo.html || fa fa-external-link-square-alt
      i18n: /internationalization.html || fa fa-globe-asia

    Third Party Services:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      Comment Systems: /comments.html || fa fa-comment-alt
      Post Widgets: /post-widgets.html || fa fa-gift
      Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
      Search Services: /search-services.html || fab fa-algolia
      Chat Services: /chat-services.html || fa fa-comments
      External Libraries: /external-libraries.html || fa fa-lightbulb

    Tag Plugins:
      default: /tag-plugins/ || fa fa-rocket
      Button: /button.html || fa fa-cube
      Caniuse: /caniuse.html || fa fa-signal
      Group Pictures: /group-pictures.html || fa fa-images
      Label: /label.html || fa fa-hat-wizard
      Link Grid: /link-grid.html || fa fa-grip-vertical
      Mermaid: /mermaid.html || fa fa-project-diagram
      Note: /note.html || fa fa-adjust
      PDF: /pdf.html || fa fa-file-pdf
      Tabs: /tabs.html || fa fa-columns

    Advanced Settings:
      default: /advanced-settings/ || fa fa-cog
      Vendors: /vendors.html || fa fa-plug
      Custom Files: /custom-files.html || fa fa-palette
      Injects: injects.html || fa fa-layer-group
      Front Matter: /front-matter.html || fa fa-edit

    Troubleshooting: /troubleshooting.html || fa fa-life-ring

  Plugins: /plugins/ || fa fa-flask
  archives: /archives/ || fa fa-archive
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  #width: 300

avatar:
  url: /images/logo.svg
  # If true, the avatar will be dispalyed in circle.
  rounded: true
  # If true, the avatar will be rotated with the cursor.
  rotated: false

# Posts / Categories / Tags in sidebar.
#site_state: true

social:
  GitHub: https://github.com/alvinau0427 || fab fa-github
  #StackOverflow: https://stackoverflow.com/alvinau0427 || fab fa-stack-overflow
  Twitter: https://twitter.com/alvinau0427 || fab fa-twitter
  #Instagram: https://instagram.com/alvinau0427 || fab fa-instagram
  #Google: https://plus.google.com/yourname || fab fa-google
  #FB Page: https://www.facebook.com/yourname || fab fa-facebook
  #YouTube: https://youtube.com/yourname || fab fa-youtube
  #Skype: skype:yourname?call|chat || fab fa-skype
  E-Mail: mailto:alvinau0427@outlook.com || fa fa-envelope

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

# Show multilingual switcher in footer.
language_switcher: false

footer:
  # Specify the year when the site was setup. If not defined, current year will be used.
  #since: 2014
  icon:
    name: fa fa-heart
    animated: false
    color: "#808080"
  copyright: Alvin Au
  powered: true


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

# Post meta display settings
post_meta:
  #item_text: true
  #created_at: true
  updated_at:
    enable: false
    #another_day: true
  #categories: true

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: true
  url: https://github.com/next-theme/theme-next-docs/edit/master/source/

# Show previous post and next post in post footer if exists
# Available values: left | right | false
#post_navigation: left


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

# Preconnect CDN for fonts and plugins.
# For more information: https://www.w3.org/TR/resource-hints/#preconnect
preconnect: false

# Set the text alignment in posts / pages.
text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify

# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: true

# Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
android_chrome_color: "#222"

codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: default
    dark: tomorrow-night
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Available values: default | flat | mac
    style: default

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/alvinau0427
  title: Fork NexT on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: false

# If true, site-subtitle will be added to index page.
# Remember to set up your site-subtitle in Hexo `_config.yml` (e.g. subtitle: Subtitle)
index_with_subtitle: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true

# Google Webmaster tools verification.
# See: https://developers.google.com/search
google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

# Math Formulas Render Support
# Warning: Please install / uninstall the relevant renderer according to the documentation.
# See: https://theme-next.js.org/docs/third-party-services/math-equations
# Server-side plugin: https://github.com/next-theme/hexo-filter-mathjax
math:
  mathjax:
    enable: true

# Easily enable fast Ajax navigation on your website.
# For more information: https://github.com/next-theme/pjax
pjax: true

# A JavaScript library for zooming images like Medium.
# Warning: Do not enable both `fancybox` and `mediumzoom`.
# For more information: https://medium-zoom.francoischalifour.com
mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

# Multiple Comment System Support
comments:
  # Lazyload all comment systems.
  lazyload: true

# Disqus
# For more information: https://disqus.com
disqus:
  enable: true
  shortname: next-theme
  count: true


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# Google Analytics
google_analytics:
  tracking_id: # <app_id>
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

# Local Search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

# Note tag (bootstrap callout)
note:
# Note tag style values:
  #  - simple    bootstrap callout old alert style. Default.
  #  - modern    bootstrap callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: true
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: -3

# Tabs tag
tabs:
  transition:
    tabs: true
    labels: true

# PDF tag
# NexT will try to load pdf files natively, if failed, pdf.js will be used.
# So, you have to install the dependency of pdf.js if you want to use pdf tag and make it available to all browsers.
# Dependencies: https://github.com/next-theme/theme-next-pdf
pdf:
  enable: false
  # Default height
  height: 500px

# Mermaid tag
mermaid:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

# Use Animate.css to animate everything.
# For more information: https://animate.style
motion:
  async: true

# It's recommended to use the same version as in `_vendors.yml` to avoid potential problems.
# Remember to use the HTTPS protocol of CDN links when you enable HTTPS on your site.
# Available values: local | jsdelivr | unpkg | cdnjs
vendors:
  internal: jsdelivr
